services:
  - type: web
    name: histology-portal-backend
    runtime: node
    buildCommand: cd client && npm install --include=dev && npm run build && cd ../server && npm install
    startCommand: cd client && npm install --include=dev && npm run build && cd ../server && npm install && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: histology-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: histology-db
    ipAllowList: []
    plan: free
    postgresMajorVersion: "15"
